infotool/urls.py
"""
Copyright (C) 2014  Rene Jablonski

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; version 2
of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from portal import views as portal_views
from booking import views as booking_views
from filebrowser.sites import site

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', portal_views.IndexView.as_view(), name='index'),
    url(r'^submit/feedback/(?P<current_site_id>\d+)/$', portal_views.submit_feedback, name='feedback'),
    url(r'^submit/report/(?P<current_site_id>\d+)/$', portal_views.submit_report, name='report'),
    url(r'^$', portal_views.IndexView.as_view(), name='index'),
    url(r'^powered-by/$', portal_views.PoweredByView.as_view(), name='powered_by'),
    url(r'^infoscreen/$', booking_views.InfoscreenView.as_view(), name='infoscreen'),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
)

site_pattern = patterns('',
    url(r'(?P<pk>\d+)/', portal_views.SiteView.as_view(), name='site'),
)

urlpatterns += i18n_patterns('',
    url(r'^$', portal_views.IndexView.as_view(), name='lang_index'),
    url(r'site/', include(site_pattern), ),
    url(r'(?P<pk>\d+)/success/$', portal_views.FormSuccessView.as_view(), name='success'),
)

portal/forms.py
"""
Copyright (C) 2014  Rene Jablonski

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; version 2
of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""
from django import forms
from portal.models import FeedbackCategory, DamageCategory, Category
from django.utils.translation import get_language
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _


class GenericContactForm(forms.Form):
    subject = forms.CharField(label=_('Subject'),
                              max_length=100)
    name = forms.CharField(label=_('Name/Group'),
                           max_length=100,
                           required=False,
                           help_text=_('Optional'))
    mail = forms.EmailField(label=_('E-Mail'),
                            required=False,
                            help_text=_('Optional'))
    message = forms.CharField(label=_('Message'),
                              widget=forms.Textarea,
                              help_text=_('Required'))

    def send_mail(self):
        category = Category.objects.filter(id=self.cleaned_data['subject']).first()
        subject = category.name
        name = self.cleaned_data['name']
        mail = self.cleaned_data['mail']
        message = self.cleaned_data['message']
        body = _('Name/Group: %(name)\nEmail: %(mail)\nMessage:\n%(message)') % {'name': name, 'mail': mail,
                                                                                 'message': message}
        # body = message
        contact = '%s %s <%s>' % (category.contact.prename, category.contact.name, category.contact.email)
        send_mail(subject, body, 'rene@p-pchen.de', (contact,), fail_silently=False)
        print 'send mail\nto: %s\nsubject: %s\nmessage:\n%s' % (contact, subject, body)


class FeedbackForm(GenericContactForm):
    categories = FeedbackCategory.objects.filter(
        is_visible=True,
        language__language_code=get_language().split('-')[0]
    ).order_by('name')
    subject = forms.ChoiceField(
        label=_('Subject'),
        widget=forms.Select,
        choices=categories.values_list('id', 'name'))


class DamageReportForm(GenericContactForm):
    categories = DamageCategory.objects.filter(
        is_visible=True,
        language__language_code=get_language().split('-')[0]
    ).order_by('name')
    subject = forms.ChoiceField(
        label=_('Subject'),
        widget=forms.Select,
        choices=categories.values_list('id', 'name'))

portal/views.py
"""
Copyright (C) 2014  Rene Jablonski

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; version 2
of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views import generic
from portal.models import Site, SpecialSite, Language, Category
from portal.forms import FeedbackForm, DamageReportForm
from django.utils.translation import get_language
from django.core import serializers
import re


def generic_context_data(context, request):

    context[u'nav_items'] = Site.objects.filter(language__language_code=get_language(),
                                                superior_site=None,
                                                is_visible=True).order_by(u'order')
    context[u'supported_languages'] = Language.objects.all().order_by(u'native')
    context[u'redirect_url'] = u'http://%s%s' % (request.get_host(),
                                                 request.get_full_path(),)
    return context


class IndexView(generic.TemplateView):
    model = SpecialSite
    template_name = u'portal/site.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update(generic_context_data(context, self.request))
        site = Site.objects.filter(language__language_code=get_language(),
                                   superior_site=None,
                                   is_visible=True,).order_by(u'order').first()
        context[u'site'] = site
        context[u'current_site_id'] = site.id
        context[u'is_selected'] = True
        return context


class SiteView(generic.DetailView):
    model = SpecialSite
    template_name = u'portal/site.html'
    context_object_name = u'site'

    def get_queryset(self):
        return Site.objects.filter(language__language_code=get_language(),
                                   is_visible=True)

    def get_context_data(self, **kwargs):
        context = super(SiteView, self).get_context_data(**kwargs)
        context.update(generic_context_data(context, self.request))
        pattern = re.compile(u'^.+/site/(?P<pk>\d+)/$')
        match = pattern.match(self.request.path_info)
        context[u'current_site_id'] = match.group(u'pk')

        return context


class FormSuccessView(generic.TemplateView):
    template_name = 'portal/contact-success.html'

    def get_context_data(self, **kwargs):
        context = super(FormSuccessView, self).get_context_data(**kwargs)
        context.update(generic_context_data(context, self.request))
        context['current_site_id'] = context['pk'];
        return context


class PoweredByView(generic.TemplateView):
    template_name = 'portal/powered-by.html'

    def get_context_data(self, **kwargs):
        context = super(PoweredByView, self).get_context_data(**kwargs)
        context.update(generic_context_data(context, self.request))
        context[u'current_site_id'] = -1
        return context


def submit_feedback(request, current_site_id):
    print request.method
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = FeedbackForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            print 'valid'
            form.send_mail()
            return HttpResponseRedirect('success/')
        else:
            pk = current_site_id
            return HttpResponseRedirect(reverse('site', args=(pk,)))


def submit_report(request, current_site_id):
    print request.method
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = DamageReportForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            print 'valid'
            form.send_mail()
            return HttpResponseRedirect('success/')
        else:
            pk = current_site_id
            return HttpResponseRedirect(reverse('site', args=(pk,)))

portal/templates/portal/base.html
{% extends "portal/generic.html" %}

{% comment "License" %}
    Copyright (C) 2014  Rene Jablonski

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; version 2
    of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
{% endcomment %}

{% load i18n %}
{% load nav_item %}
{% load sub_sites %}
{% load staticfiles %}

{% get_current_language as LANGUAGE_CODE %}

{% block generic_css_style %}
    <link type="text/css" rel="stylesheet" href="{% static "css/portal/base.css" %}" charset="utf-8" media="all">
    {% block base_css_style %}{% endblock %}
{% endblock %}

{% block generic_js_script %}
    <script type="text/javascript" src="{% static "js/portal/base.js" %}" charset="utf-8"></script>
    {% block base_js_script %}{% endblock %}
{% endblock %}

{% block header_red %}
    <a id="navigation-toggle" href="javascript:;" onclick="toggleNavigation();" alt="navigation toggle">
        <p><span class="icon-menu2"></span>{% trans 'Menu' %}</p>
    </a>
{% endblock %}

{% block container %}
    <div id="main">
        <div id="sidebar">
            {% block sidebar %}
                <nav id="navigation">
                    <ul>
                        {% for item in nav_items %}
                            <li id="nav-item-{{ item.id }}">
                                <span>{% nav_item item.id %}</span>
                                {% sub_sites item.id %}
                                {% if sub_nav_items %}
                                    {% if is_sub_item_selected == True %}
                                        {% comment %}<span id="toggle-icon-{{ item.id }}" class="icon-minus3"></span>{% endcomment %}
                                        <ul id="sub-{{ item.id }}" style="display: inherit;">
                                    {% else %}
                                        {% comment %}<span id="toggle-icon-{{ item.id }}" class="icon-plus3"></span>{% endcomment %}
                                        <ul id="sub-{{ item.id }}">
                                    {% endif %}
                                {% for sub_item in sub_nav_items %}
                                    <li id="nav-item-{{ sub_item.id }}">
                                        <span>
                                            {% nav_item sub_item.id %}
                                        </span>
                                    </li>
                                {% endfor %}
                                </ul>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </nav>
                <ul id="internet-form">
                    <li>
                    <span>
                        <a href="javascript:;" data-id="internet"
                           onclick="toggleSubNavigation(this);">{% trans 'Internet' %}</a>
                    </span>
                        <ul id="sub-internet">
                            <li>
                                <form method="post" action="">
                                    {% csrf_token %}
                                    <input name="redirurl" type="hidden" value="{{ redirect_url }}">
                                    <input name="auth_user" type="text" size="15" placeholder="{% trans 'User' %}">
                                    <input name="auth_pass" type="password" size="15" placeholder="{% trans 'Password' %}">
                                    <input name="accept" type="submit" value="{% trans 'Login' %}">
                                </form>
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul id="options-wrapper">
                    <li>
                        <span>
                            <a href="javascript:;" data-id="options"
                               onclick="toggleSubNavigation(this);">{% trans "Options" %}</a>
                        </span>
                        <ul id="sub-options">
                            <li id="language-options">
                                <span>{% trans 'Language' %}</span>
                                <span>
                                    <select onchange="setLang(this)">
                                        {% for language in supported_languages %}
                                            <option value="{{ language.language_code }}"
                                                    {% if language.language_code == LANGUAGE_CODE %}
                                                    selected="selected"
                                                    {% endif %}
                                                    >{{ language.native }}</option>
                                        {% endfor %}
                                    </select>
                                </span>
                            </li>
                            <li id="view-options">
                                <span>{% trans 'Font Size' %}</span>
                                <span>
                                    <a href="javascript:;" onclick="changeFontSize(-1);"
                                       alt="{% trans 'decrease' %}" title="{% trans 'decrease' %}">
                                        <span class="icon-zoomout"></span>
                                    </a>
                                    <a href="javascript:;" onclick="changeFontSize(1);"
                                       alt="{% trans 'increase' %}" title="{% trans 'increase' %}">
                                        <span class="icon-zoomin"></span>
                                    </a>
                                    <a href="javascript:;" onclick="setBaseFontSize(16);"
                                       alt="{% trans 'reset' %}" title="{% trans 'reset' %}">
                                        <span class="icon-search"></span>
                                    </a>
                                </span>
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul id="powered-by">
                    <li>
                        <span><a href="{% url 'powered_by' %}" alt="powered by">powered by Beuth Hochschule Berlin</a></span>
                    </li>
                </ul>
            {% endblock %}
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

portal/templates/portal/contact-form.html
{% comment "License" %}
    Copyright (C) 2014  Rene Jablonski

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; version 2
    of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
{% endcomment %}

{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

{% comment %}{% block title %}{% trans 'Contact' %}{% endblock %}{% endcomment %}

{% block js_script %}
    <script type="text/javascript">
        {% autoescape off %}
            var placeholders = JSON.parse('{{ placeholders }}');
        {% endautoescape %}

        $(function() {
            $('#id_subject').on('change', function(){
                onSubjectChange();
            });
            onSubjectChange();
        });

        var onSubjectChange = function() {
            var selectedSubject = $('#id_subject').val();
            console.log(selectedSubject);
            for(var i=0; i < placeholders.length; i++) {
                console.log(placeholders);
                if(placeholders[i].pk == selectedSubject) {
                    $('#id_message').attr('placeholder', placeholders[i].fields.placeholder);
                }
            };
        }
    </script>
{% endblock %}

{% block content %}
    <form action="{% url view_name current_site_id %}" method="post">
        {% csrf_token %}
        {# Include the hidden fields #}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {# Include the visible fields #}
        {% for field in form.visible_fields %}
            <div class="fieldWrapper">
                {{ field.errors }}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="field">{{ field }}</div>
            </div>
            <div class="hintWrapper">
                <label></label>
                <div class="hint">{{ field.help_text }}</div>
            </div>
        {% endfor %}
        <div class="fieldWrapper">
            <label></label>
            <div class="field">
                <input type="submit" value="{% trans 'Submit' %}" />
            </div>
        </div>
    </form>
{% endblock %}

portal/templates/portal/contact-success.html
{% extends "portal/base.html" %}

{% comment "License" %}
    Copyright (C) 2014  Rene Jablonski

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; version 2
    of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
{% endcomment %}

{% load i18n %}

{% block title %}{% trans 'Success' %}{% endblock %}

{% block content %}
    <p>{% trans 'The message was sent successfully.' %}</p>
    <p><a href="{% url 'site' pk %}">{% trans 'back' %}</a></p>
{% endblock %}

portal/templates/portal/generic.html
<!DOCTYPE html>
{% comment "License" %}
    Copyright (C) 2014  Rene Jablonski

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; version 2
    of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
{% endcomment %}

{% load i18n %}
{% load staticfiles %}

{% get_current_language as LANGUAGE_CODE %}

<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width" name="viewport">
        <title>{% block title %}{% endblock %}</title>
        <link type="text/css" rel="stylesheet" href="{% static "css/portal/generic.css" %}" charset="utf-8" media="all">
        <link type="text/css" rel="stylesheet" href="{% static "css/portal/icons.css" %}" charset="utf-8" media="all">
        <link type="text/css" rel="stylesheet" href="{% static "css/portal/magnific-popup.css" %}" charset="utf-8" media="all">
        {% block generic_css_style %}{% endblock %}
        <script type="text/javascript" src="{% static "js/portal/jquery-1.11.1.min.js" %}" charset="utf-8"></script>
        <script type="text/javascript" src="{% static "js/portal/jquery.cookie.js" %}" charset="utf-8"></script>
        <script type="text/javascript" src="{% static "js/portal/jquery.magnific-popup.min.js" %}" charset="utf-8"></script>
        {% block generic_js_script %}{% endblock %}
    </head>
    <body>
        <div id="container">
            <div id="header">
                {% comment %}<div id="logo" class="white-bg">Jugendbildungsstätte Kurt Löwenstein</div>{% endcomment %}
                <div class="red-bg cell">
                    {% block header_red %}{% endblock %}
                    <span>&nbsp;</span>
                </div>
            </div>
            {% block container %}{% endblock %}
        </div>
    </body>
</html>

portal/templates/portal/nav-item.html
{% comment "License" %}
    Copyright (C) 2014  Rene Jablonski

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; version 2
    of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
{% endcomment %}

{% load i18n %}
{% load sub_sites %}

{% get_current_language as LANGUAGE_CODE %}

{% if nav_item %}

    {% sub_sites nav_item.id %}

    <a id="link-{{ nav_item.id }}" data-id="{{ nav_item.id }}"
    {% if is_selected == True and sub_nav_items %}
        class="selected" href="javascript:;" onclick="toggleSubNavigation(this);"
    {% elif is_selected == True %}
        class="selected" href="{% url 'site' nav_item.id %}"
    {% elif sub_nav_items %}
        href="javascript:;" onclick="toggleSubNavigation(this);"
    {% else %}
        href="{% url 'site' nav_item.id %}"
    {% endif %}
        >{{ nav_item.title }}</a>
{% endif %}

portal/templates/portal/nav_item.html
{% comment "License" %}
    Copyright (C) 2014  Rene Jablonski

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; version 2
    of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
{% endcomment %}

{% load i18n %}
{% load sub_sites %}

{% get_current_language as LANGUAGE_CODE %}

{% sub_sites nav_item.id %}

<a id="link-{{ nav_item.id }}" data-id="{{ nav_item.id }}"
        {% if is_selected == True and sub_nav_items %}
    class="selected" href="javascript:;" onclick="toggleSubNavigation(this);"
{% elif is_selected == True %}
    class="selected" href="/{{ LANGUAGE_CODE }}/site/{{ nav_item.id }}"
{% elif sub_nav_items %}
    href="javascript:;" onclick="toggleSubNavigation(this);"
{% else %}
    href="/{{ LANGUAGE_CODE }}/site/{{ nav_item.id }}"
{% endif %}
    >{{ nav_item.title }}</a>

portal/templates/portal/powered-by.html
{% extends "portal/base.html" %}

{% comment "License" %}
    Copyright (C) 2014  Rene Jablonski

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; version 2
    of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
{% endcomment %}

{% block title %}powered by Beuth Hochschule Berlin{% endblock %}

{% block content %}
    <p>
        This CMS was developed during course "Projektmanagement" at
        <a href="http://beuth-hochschule.de" title="Beuth Hochschule für Technik Berlin">Beuth Hochschule für Technik Berlin, University of Applied Sciences</a>
        in summer 2014.
    </p>
    <br />
    <p>
        The source code is released under <a href="http://www.gnu.org/licenses/gpl-2.0.txt" title="GPL v2">GNU General Public License version 2</a>.
        You can find the code at <a href="https://github.com/SonRiab/infotool" title="github">https://github.com/SonRiab/infotool</a>.
    </p>
    <br>
    <p>Team members:</p>
    <br>
    <p>Andre Groß</p>
    <p>Benno Schwigon</p>
    <p>Johan Borchert</p>
    <p>Rene Jablonski</p>
    <br>
    <p>Special thx to</p>
    <br>
    <p><a href="https://www.djangoproject.com/">Django Project</a></p>
    <p><a href="https://github.com/aljosa/django-tinymce">Django-TinyMCE</a></p>
    <p><a href="http://pythonhosted.org/pytz/">pytz</a></p>
    <p><a href="https://github.com/sehmaschine/django-filebrowser">Django FileBrowser</a></p>
    <p><a href="http://python-pillow.github.io/">pillow</a></p>
{% endblock %}